language: node_js
node_js: 10.15.1

install:
  - npm install -g @angular/cli@7.3.1
  - npm install

script:
  - ng lint
  - ng test
  - ng e2e
  - ng build --prod --base-href https://t-palmer.github.io/travis-demo/
