language: node_js
node_js: 10

addons:
  chrome: stable

install:
  - npm install -g @angular/cli@7.3.1
  - npm install
  # Fix error: Chrome version must be between 71 and 75
  - cd node_modules/protractor
  - npm i webdriver-manager@latest

script:
  - ng lint
  - ng test --watch=false --browsers=ChromeHeadless
  - ng e2e
  - ng build
