language: node_js
node_js: 10

addons:
  chrome: stable

install:
  - npm install -g @angular/cli@7.3.1
  - npm install

script:
  - ng lint
  - ng test --watch=false --browsers=ChromeHeadless
  - ng e2e
  - ng build
